import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
    <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    <header
        className="fixed inset-x-0 top-0 z-30 mx-auto w-full max-w-screen-md border border-gray-100 bg-white/80 py-3 shadow backdrop-blur-lg md:top-6 md:rounded-3xl lg:max-w-screen-lg">
        <div className="px-4">
            <div className="flex items-center justify-between">
                <div className="flex shrink-0">
                    <Link aria-current="page" className="flex items-center" href="/">
                        <img className="h-7 w-auto"
                             src="Logo.png"
                             alt="93Moov"/>
                        <p className="sr-only">93Moove</p>
                    </Link>
                </div>
                <div className="hidden md:flex md:items-center md:justify-center md:gap-5">
                    <Link className="inline-block rounded-lg px-2 py-1 text-sm font-medium text-gray-900 transition-all duration-200 hover:bg-gray-100 hover:text-gray-900"
                          href="/prix">Les prix</Link>
                </div>
                <div className="flex items-center justify-end gap-3">
                    <a className="hidden items-center justify-center rounded-xl bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 transition-all duration-150 hover:bg-gray-50 sm:inline-flex"
                       href="/login">S&#39;inscrire</a>
                    <a className="inline-flex items-center justify-center rounded-xl bg-blue-600 px-3 py-2 text-sm font-semibold text-white shadow-sm transition-all duration-150 hover:bg-blue-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600"
                       href="/login">Se connecter</a>
                </div>
            </div>
        </div>
    </header>
    {children}
    <footer className="mt-20 xl:mt-32 mx-auto w-full relative text-center text-white">
        <div className="px-6 py-8 md:py-14 xl:pt-20 xl:pb-12">
            <h2 className="font-bold text-3xl xl:text-4xl leading-snug">
                Ready to get your productivity back?<br/>Start your free trial today.
            </h2>
            <a className="mt-8 xl:mt-12 px-12 py-5 text-lg font-medium leading-tight inline-block bg-orange-400 rounded-full shadow-xl border border-transparent hover:bg-sky-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-sky-999 focus:ring-sky-500"
               href="#">Get
                started</a>
            <div className="mt-14 xl:mt-20">
                <nav className="flex flex-wrap justify-center text-lg font-medium">
                    <div className="px-5 py-2"><a href="#">Contact</a></div>
                    <div className="px-5 py-2"><a href="#">Prix</a></div>
                    <div className="px-5 py-2"><a href="#">Terms</a></div>
                    <div className="px-5 py-2"><a href="#">Twitter</a></div>
                </nav>
                <p className="mt-7 text-base">© 2023 XYZ, LLC</p>
            </div>
        </div>
    </footer>
    </body>
    </html>
  );
}
