import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
    <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    <header className="flex mx-auto justify-between items-center max-w-[1300px] py-4 ">
        <div className="flex items-center gap-3">
            <img src="logow.png" alt="93Moove" width={90} height={90}/>

        </div>
        <nav className="hidden sm:inline-block">
            <ul className="flex gap-3 md:gap-5 lg:gap-10">
                <li className="uppercase font-bold text-xs text-white"><a href="#">ABOUT</a></li>
                <li className="uppercase font-bold text-xs text-white"><a href="#">SERVICES</a></li>
                <li className="uppercase font-bold text-xs text-white"><a href="#">TECHNOLOGIES</a></li>
                <li className="uppercase font-bold text-xs text-white"><a href="#">HOW TO</a></li>
            </ul>
        </nav>
        <div className="hidden sm:flex gap-3 md:gap-5 lg:gap-9">
            <button
                className="uppercase font-bold text-xs text-white border-2 border-white rounded-[40px] py-1 px-3  md:py-2 lg:py-4 md:px-4 lg:px-9 ">
                Inscription
            </button>
            <button
                className="uppercase font-bold text-xs rounded-[40px] py-1 px-3 md:py-2 lg:py-4 md:px-4 lg:px-9 text-[#302c42]  bg-gradient-to-r from-[#8176AF] to-[#C0B7E8]">
                Connexion
            </button>
        </div>
        <button className="sm:hidden inline-block">
            <svg width="33" height="26" viewBox="0 0 33 26" fill="none" xmlns="http://www.w3.org/2000/svg">
                <rect width="33" height="3.71429" rx="1.85714" fill="url(#paint0_linear_13_83)"></rect>
                <rect y="22.2857" width="33" height="3.71429" rx="1.85714" fill="url(#paint1_linear_13_83)"></rect>
                <rect x="9" y="11.1429" width="24" height="3.71429" rx="1.85714"
                      fill="url(#paint2_linear_13_83)"></rect>
                <defs>
                    <linearGradient id="paint0_linear_13_83" x1="-8.62252e-09" y1="3.46667" x2="36.0395" y2="3.46666"
                                    gradientUnits="userSpaceOnUse">
                        <stop stop-color="#C0B7E8"></stop>
                        <stop offset="1" stop-color="#8176AF"></stop>
                    </linearGradient>
                    <linearGradient id="paint1_linear_13_83" x1="-3.90789" y1="26" x2="33" y2="26"
                                    gradientUnits="userSpaceOnUse">
                        <stop stop-color="#C0B7E8"></stop>
                        <stop offset="1" stop-color="#8176AF"></stop>
                    </linearGradient>
                    <linearGradient id="paint2_linear_13_83" x1="5.21062" y1="13" x2="33.0001" y2="13"
                                    gradientUnits="userSpaceOnUse">
                        <stop stop-color="#C0B7E8"></stop>
                        <stop offset="1" stop-color="#8176AF"></stop>
                    </linearGradient>
                </defs>
            </svg>
        </button>
    </header>
    {children}
    <footer className="mt-20 xl:mt-32 mx-auto w-full relative text-center text-white">
        <div className="px-6 py-8 md:py-14 xl:pt-20 xl:pb-12">
            <h2 className="font-bold text-3xl xl:text-4xl leading-snug">
                Commencez maintenant.
            </h2>
            <a className="mt-8 xl:mt-12 px-12 py-5 text-lg font-medium leading-tight inline-block bg-orange-400 rounded-full shadow-xl border border-transparent hover:bg-sky-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-sky-999 focus:ring-sky-500"
               href="#">S'inscire</a>
            <div className="mt-14 xl:mt-20">
                <nav className="flex flex-wrap justify-center text-lg font-medium">
                    <div className="px-5 py-2"><a href="#">Contact</a></div>
                    <div className="px-5 py-2"><a href="#">Prix</a></div>
                    <div className="px-5 py-2"><a href="#">Terms</a></div>
                    <div className="px-5 py-2"><a href="#">Twitter</a></div>
                </nav>
                <p className="mt-7 text-base">&copy; Organisme du lycée Auguste blanqui</p>
            </div>
        </div>
    </footer>
    </body>
    </html>
  );
}
